### ISSUE TITLE
Naming of PostgresRepository

### ISSUE THREAD

**Issue by sonallux** [jvalue/node-dry-pg#5]
> There are only two hard things in Computer Science: cache invalidation and naming things.

I would propose to change the name of the exported `PostgresRepository` class. For me, the `Repository` part does imply that it has something to do with the [Repository design pattern](https://martinfowler.com/eaaCatalog/repository.html). But that's not the case, because the class does neither have domain nor data mapping knowledge. Instead, it is just a tiny wrapper around the `pg` library.

I would change the name to `PostgresDatabase` or `PostgresClient`. @georg-schwarz what do you think about that or do you have other name suggestions?

**Comment by georg-schwarz** [comment]
Hm you are right! I think naming it as client is better than database, but I don't have a better name either..

**Comment by sonallux** [comment]
> Hm you are right! I think naming it as client is better than database, but I don't have a better name either..

I also think `PostgresClient` is better. Maybe @lunedis has a better name?
